Adding Swift Package Manager manifest file.
indragiek/InAppViewDebugger pull request #12
Opened 2020-06-26 00:49 UTC by McProb

2020-06-26 14:15 UTC, tjh12c commented
@indragiek talked to you on Twitter, my coworker Rob ended up adding the SPM compatibility rather than myself. Let us know if anything looks off!

2020-06-29 06:17 UTC, indragiek requested changes
Just a couple nits to make this more concise, thanks to both of you for contributing this!

2020-06-29 06:17 UTC, indragiek commented on Package.swift
> +    ],
nit: drop this boilerplate

2020-06-29 06:17 UTC, indragiek commented on Package.swift
> +        // Products define the executables and libraries a package produces, and make them visible to other packages.
nit: remove comment

2020-06-29 06:17 UTC, indragiek commented on Package.swift
> +        // Targets can depend on other targets in this package, and on products in packages this package depends on.
nit: remove comment

2020-06-29 16:09 UTC, McProb commented
Happy to make the file more concise.  I think it will be important to note that using package manager with this framework requires Xcode 12 or higher in order to include the xcassets.  I think this is good to go.  Thanks again!

2020-06-29 19:26 UTC, indragiek approved these changes

2020-06-29 19:27 UTC, indragiek commented
Thank you @McProb!

2020-06-29 19:27 UTC, merged